# Generated by Django 6.0.7 on 2026-08-03 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('os_info', models.CharField(blank=True, default='', max_length=512)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('local_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cpu_info', models.CharField(blank=True, default='', max_length=512)),
                ('cpu_cores', models.IntegerField(blank=True, null=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('ram_total', models.BigIntegerField(blank=True, null=True)),
                ('ram_used', models.BigIntegerField(blank=True, null=True)),
                ('ram_percent', models.FloatField(blank=True, null=True)),
                ('drives', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
