# Generated by Django 6.0.7 on 2026-08-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_backupactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAgent',
            fields=[
                ('agent_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
