# Generated by Django 6.0.7 on 2026-08-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_deletedagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentreport',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
