# Generated by Django 6.0.7 on 2026-08-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_agentreport_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedagent',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deletedagent',
            name='mac_address',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='deletedagent',
            name='agent_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
