# Generated by Django 5.2.5 on 2026-08-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_deletedagent_hostname_deletedagent_mac_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentreport',
            options={'ordering': ['-first_seen', '-id']},
        ),
        migrations.AddField(
            model_name='backupactivity',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
