# Generated by Django 5.2.5 on 2026-08-18 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alter_agentreport_options_backupactivity_hostname'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS monitor_uploadedfile;",
            reverse_sql=""
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('drive_letter', models.CharField(max_length=10)),
                ('file_path', models.CharField(max_length=700)),
                ('file_name', models.CharField(max_length=512)),
                ('file_extension', models.CharField(blank=True, default='', max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('file_content', models.BinaryField()),
                ('is_deleted_on_client', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='monitor.agentreport')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('hostname', 'file_path')},
            },
        ),
    ]
