# Generated by Django 5.2.5 on 2026-08-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_alter_uploadedfile_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentreport',
            name='sync_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='agentreport',
            name='sync_status',
            field=models.CharField(blank=True, default='Idle', max_length=128),
        ),
        migrations.AddField(
            model_name='agentreport',
            name='sync_total_files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentreport',
            name='sync_uploaded_files',
            field=models.IntegerField(default=0),
        ),
    ]
